//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSClass
    {
        public POSClass()
        {
            
        }
    
        public string posID { get; set; }
        public DateTime posOrderDate { get; set; }
        public DateTime posEntryDate { get; set; }
        public DateTime posEndDate { get; set; }
        public string posDesc { get; set; }
        public bool posStatus { get; set; }
        public decimal posTotAmount { get; set; }
        public int posTotQty { get; set; }
        public string cID { get; set; }
        public string spID { get; set; }
    
        
    }
}
