//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSDetail
    {
        public string posdID { get; set; }
        public string posdDesc { get; set; }
        public bool posdStatus { get; set; }
        public decimal posdAmount { get; set; }
        public int posdQty { get; set; }
        public string posID { get; set; }
        public string pID { get; set; }
    
        
    }
}
