//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            
        }
    
        public string pID { get; set; }
        public string pName { get; set; }
        public decimal pPrice { get; set; }
        public int pdQty { get; set; }
        public bool pStatus { get; set; }
        public string pDesc { get; set; }
        public string ptID { get; set; }
    
    }
}
