//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPerson
    {
        public SalesPerson()
        {

        }
    
        public string spID { get; set; }
        public string spFName { get; set; }
        public string spLName { get; set; }
        public string spCNIC { get; set; }
        public string spEmail { get; set; }
        public string spDesc { get; set; }
        public bool spStatus { get; set; }
    
    }
}
